/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  current_view: "project",
  current_project_id: "",
  current_task_id: ""
};

export default awsmobile;
